/*\n  # Storage Trigger für automatische Photo-Erfassung\n\n  ## Änderungen\n\n  ### 1. Index auf photos.captured_at\n  - Erstellt Index für effiziente Zeitbereich-Abfragen\n  - Sortiert nach captured_at DESC für schnelle neueste-zuerst Abfragen\n\n  ### 2. Trigger Function: handle_new_storage_object\n  - Wird ausgelöst bei INSERT in storage.objects\n  - Filtert nach bucket_id='test'\n  - Erstellt automatisch photos-Record mit:\n    - storage_bucket = bucket_id\n    - storage_path = name (Pfad der Datei)\n    - captured_at = created_at (Upload-Zeitstempel)\n    - created_at = now()\n  - ON CONFLICT DO NOTHING verhindert Duplikate\n\n  ### 3. Trigger: on_storage_object_created\n  - Hört auf INSERT Events in storage.objects\n  - Führt handle_new_storage_object() aus\n\n  ## Zweck\n  Automatische Synchronisation von Storage-Uploads mit photos-Tabelle\n  für nahtlose Integration mit der Galerie-Ansicht.\n*/\n\n-- Index auf captured_at für effiziente Zeitbereich-Abfragen\nCREATE INDEX IF NOT EXISTS idx_photos_captured_at \n  ON photos(captured_at DESC);
\n\n-- Function die bei Storage-Upload ausgeführt wird\nCREATE OR REPLACE FUNCTION handle_new_storage_object()\nRETURNS TRIGGER AS $$\nBEGIN\n  -- Nur für bucket 'test' ausführen\n  IF NEW.bucket_id = 'test' THEN\n    -- Photo-Record erstellen (on conflict do nothing für Sicherheit)\n    INSERT INTO public.photos (\n      storage_bucket,\n      storage_path,\n      captured_at,\n      created_at\n    )\n    VALUES (\n      NEW.bucket_id,\n      NEW.name,\n      NEW.created_at,\n      now()\n    )\n    ON CONFLICT (storage_bucket, storage_path) DO NOTHING;
\n  END IF;
\n  \n  RETURN NEW;
\nEND;
\n$$ LANGUAGE plpgsql SECURITY DEFINER;
\n\n-- Trigger erstellen (drop first wenn bereits vorhanden)\nDROP TRIGGER IF EXISTS on_storage_object_created ON storage.objects;
\n\nCREATE TRIGGER on_storage_object_created\n  AFTER INSERT ON storage.objects\n  FOR EACH ROW\n  EXECUTE FUNCTION handle_new_storage_object();
;
