/*\n  # Add Stripe Payment Fields and Speed Extraction\n\n  ## Changes\n\n  ### 1. Extend photos table\n  - `price_cents` (integer) - Photo price in cents, default 300 (3.00 EUR)\n  - `currency` (text) - Currency code, default 'eur'\n  - `is_paid` (boolean) - Global paid flag (optional), default false\n  - `stripe_product_id` (text, nullable) - Stripe product reference\n  - `stripe_price_id` (text, nullable) - Stripe price reference\n  - Index on is_paid for filtering\n\n  ### 2. Extend purchases table\n  - `stripe_checkout_session_id` (text, unique) - Stripe checkout session ID\n  - `stripe_payment_intent_id` (text, nullable) - Stripe payment intent ID\n  - `amount_cents` (integer) - Amount paid in cents\n  - `currency` (text) - Currency used\n  - `paid_at` (timestamptz, nullable) - When payment completed\n  - Additional indexes on status and photo_id\n\n  ### 3. Speed extraction function\n  - `parse_speed_kmh(path text)` - Extracts speed from filename pattern like "34,48 km/h"\n  - Returns numeric value with decimal point\n  - Returns null if pattern not found\n\n  ### 4. Update storage trigger\n  - Automatically extracts speed_kmh from filename on insert\n\n  ### 5. Backfill existing photos\n  - Updates speed_kmh for all existing photos where null\n*/\n\n-- =====================================================\n-- PHOTOS TABLE: Add payment fields\n-- =====================================================\n\n-- Add price_cents column\nDO $$\nBEGIN\n  IF NOT EXISTS (\n    SELECT 1 FROM information_schema.columns\n    WHERE table_schema = 'public' AND table_name = 'photos' AND column_name = 'price_cents'\n  ) THEN\n    ALTER TABLE photos ADD COLUMN price_cents integer NOT NULL DEFAULT 300;
\n  END IF;
\nEND $$;
\n\n-- Add currency column\nDO $$\nBEGIN\n  IF NOT EXISTS (\n    SELECT 1 FROM information_schema.columns\n    WHERE table_schema = 'public' AND table_name = 'photos' AND column_name = 'currency'\n  ) THEN\n    ALTER TABLE photos ADD COLUMN currency text NOT NULL DEFAULT 'eur';
\n  END IF;
\nEND $$;
\n\n-- Add is_paid column\nDO $$\nBEGIN\n  IF NOT EXISTS (\n    SELECT 1 FROM information_schema.columns\n    WHERE table_schema = 'public' AND table_name = 'photos' AND column_name = 'is_paid'\n  ) THEN\n    ALTER TABLE photos ADD COLUMN is_paid boolean NOT NULL DEFAULT false;
\n  END IF;
\nEND $$;
\n\n-- Add stripe_product_id column\nDO $$\nBEGIN\n  IF NOT EXISTS (\n    SELECT 1 FROM information_schema.columns\n    WHERE table_schema = 'public' AND table_name = 'photos' AND column_name = 'stripe_product_id'\n  ) THEN\n    ALTER TABLE photos ADD COLUMN stripe_product_id text;
\n  END IF;
\nEND $$;
\n\n-- Add stripe_price_id column\nDO $$\nBEGIN\n  IF NOT EXISTS (\n    SELECT 1 FROM information_schema.columns\n    WHERE table_schema = 'public' AND table_name = 'photos' AND column_name = 'stripe_price_id'\n  ) THEN\n    ALTER TABLE photos ADD COLUMN stripe_price_id text;
\n  END IF;
\nEND $$;
\n\n-- Create index on is_paid\nCREATE INDEX IF NOT EXISTS idx_photos_is_paid ON photos(is_paid);
\n\n-- =====================================================\n-- PURCHASES TABLE: Add Stripe fields\n-- =====================================================\n\n-- Add stripe_checkout_session_id column\nDO $$\nBEGIN\n  IF NOT EXISTS (\n    SELECT 1 FROM information_schema.columns\n    WHERE table_schema = 'public' AND table_name = 'purchases' AND column_name = 'stripe_checkout_session_id'\n  ) THEN\n    ALTER TABLE purchases ADD COLUMN stripe_checkout_session_id text;
\n  END IF;
\nEND $$;
\n\n-- Add unique constraint on stripe_checkout_session_id\nDO $$\nBEGIN\n  IF NOT EXISTS (\n    SELECT 1 FROM pg_constraint WHERE conname = 'purchases_stripe_checkout_session_id_key'\n  ) THEN\n    ALTER TABLE purchases ADD CONSTRAINT purchases_stripe_checkout_session_id_key \n      UNIQUE (stripe_checkout_session_id);
\n  END IF;
\nEND $$;
\n\n-- Add stripe_payment_intent_id column\nDO $$\nBEGIN\n  IF NOT EXISTS (\n    SELECT 1 FROM information_schema.columns\n    WHERE table_schema = 'public' AND table_name = 'purchases' AND column_name = 'stripe_payment_intent_id'\n  ) THEN\n    ALTER TABLE purchases ADD COLUMN stripe_payment_intent_id text;
\n  END IF;
\nEND $$;
\n\n-- Add amount_cents column\nDO $$\nBEGIN\n  IF NOT EXISTS (\n    SELECT 1 FROM information_schema.columns\n    WHERE table_schema = 'public' AND table_name = 'purchases' AND column_name = 'amount_cents'\n  ) THEN\n    ALTER TABLE purchases ADD COLUMN amount_cents integer;
\n  END IF;
\nEND $$;
\n\n-- Add currency column to purchases\nDO $$\nBEGIN\n  IF NOT EXISTS (\n    SELECT 1 FROM information_schema.columns\n    WHERE table_schema = 'public' AND table_name = 'purchases' AND column_name = 'currency'\n  ) THEN\n    ALTER TABLE purchases ADD COLUMN currency text;
\n  END IF;
\nEND $$;
\n\n-- Add paid_at column\nDO $$\nBEGIN\n  IF NOT EXISTS (\n    SELECT 1 FROM information_schema.columns\n    WHERE table_schema = 'public' AND table_name = 'purchases' AND column_name = 'paid_at'\n  ) THEN\n    ALTER TABLE purchases ADD COLUMN paid_at timestamptz;
\n  END IF;
\nEND $$;
\n\n-- Create indexes for efficient queries\nCREATE INDEX IF NOT EXISTS idx_purchases_status ON purchases(status);
\nCREATE INDEX IF NOT EXISTS idx_purchases_photo_id ON purchases(photo_id);
\n\n-- =====================================================\n-- SPEED EXTRACTION FUNCTION\n-- =====================================================\n\n-- Function to parse speed from filename\n-- Extracts patterns like "34,48 km/h" or "34.48 km/h"\n-- Returns numeric value with decimal point\nCREATE OR REPLACE FUNCTION parse_speed_kmh(path text)\nRETURNS numeric AS $$\nDECLARE\n  speed_match text;
\n  speed_value numeric;
\nBEGIN\n  -- Try to extract speed pattern: digits with comma or dot followed by km/h\n  -- Pattern matches: "123,45 km/h" or "12.34km/h" (with optional space)\n  speed_match := (regexp_matches(path, '(\\d{1,3}[,\\.]\\d{1,2})\\s*km/h', 'i'))[1];
\n  \n  IF speed_match IS NULL THEN\n    RETURN NULL;
\n  END IF;
\n  \n  -- Replace comma with dot for numeric conversion\n  speed_match := replace(speed_match, ',', '.');
\n  \n  -- Convert to numeric\n  speed_value := speed_match::numeric;
\n  \n  RETURN speed_value;
\nEXCEPTION\n  WHEN OTHERS THEN\n    RETURN NULL;
\nEND;
\n$$ LANGUAGE plpgsql IMMUTABLE;
\n\n-- =====================================================\n-- UPDATE STORAGE TRIGGER TO EXTRACT SPEED\n-- =====================================================\n\n-- Enhanced function that extracts speed from filename\nCREATE OR REPLACE FUNCTION handle_new_storage_object()\nRETURNS TRIGGER AS $$\nBEGIN\n  -- Only process for bucket 'test'\n  IF NEW.bucket_id = 'test' THEN\n    -- Create photo record with speed extraction\n    INSERT INTO public.photos (\n      storage_bucket,\n      storage_path,\n      captured_at,\n      speed_kmh,\n      created_at\n    )\n    VALUES (\n      NEW.bucket_id,\n      NEW.name,\n      NEW.created_at,\n      parse_speed_kmh(NEW.name),\n      now()\n    )\n    ON CONFLICT (storage_bucket, storage_path) DO NOTHING;
\n  END IF;
\n  \n  RETURN NEW;
\nEND;
\n$$ LANGUAGE plpgsql SECURITY DEFINER;
\n\n-- =====================================================\n-- BACKFILL SPEED FOR EXISTING PHOTOS\n-- =====================================================\n\n-- Update existing photos to extract speed from their storage_path\nUPDATE photos\nSET speed_kmh = parse_speed_kmh(storage_path)\nWHERE speed_kmh IS NULL AND storage_path IS NOT NULL;
;
